name: Formatter

on:
  workflow_dispatch:

jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      # - name: Install System Dependencies
        # run: |
          # sudo apt-get update
          # sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libmbedtls-dev libpng-dev libturbojpeg-dev libuv1-dev libvorbis-dev
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Formatter
        run: |
          haxelib --quiet install formatter
      - name: Format
        run: haxelib run formatter -s ./source
      - name: Push To Github
        run: |
          rm -rR ./haxe-4.2.5-linux64
          rm -rR ./neko-2.3.0-linux64
          ls -la
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Runned Formatter" || true
          git push -u origin main
